### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data3/viton/viton-hd/test/im_sketch_unpaired/05006_00_11001_00.png'

### ISSUE THREAD

**Issue by zhangtao22** [aimagelab/multimodal-garment-designer#5]
you mentioned this
|---- Test
.
|-------- im_sketch
|-------- im_sketch_unpaired
but from the dataset I downloaded from Viton-HD Multimodal （https://drive.google.com/file/d/1Z2b9YkyBPA_9ZDC54Y5muW9Q8yfAqWSH/view），there is no this fold. 
My com is python eval.py --dataset_path /data3/viton/viton-hd --batch_size 1 --mixed_precision fp16 --output_dir /data3/viton/out/v --save_name t1 --num_workers_test 1 --sketch_cond_rate 0.2 --dataset vitonhd --start_cond_rate 0.0
Could you give me some instructions?Thx

**Comment by omedivad** [comment]
Hello @zhangtao22,

Thanks for your interest in our work.

I checked the Viton-HD Multimodal folder, and the file is in there, so the test/im_sketch_unpaired/05006_00_11001_00.png. 
I think the problem relies on the "test" folder name in the dataset folder. It should be "test" instead of "Test". 

I modified the README accordingly. Please, in your dataset folder, rename the "Test" folder as "test" and let me know if you can run the code.

Thanks and best regards.

Davide

**Comment by zhangtao22** [comment]
![image](https://github.com/aimagelab/multimodal-garment-designer/assets/35836562/bfb998db-c673-4439-aeab-d0e60b33420d)
I checked the viton-hd fold again, there is no test/im_sketch_unpaired/

**Comment by zhangtao22** [comment]
I should merge two fold,got it.Thank you!
